# mkdocs.yml
site_name: "Nwabel"

theme:
  name: shadcn
  show_title: true # show the title in the top bar
  show_stargazers: true # show the stargazers in the top bar
  pygments_style: # default styles 
        light: shadcn-light
        dark: github-dark
  icon: heroicons:bug-ant # use the shadcn svg if not defined
  topbar_sections: true # NEW!
  katex_options: # optional
    macros: # example of macros
      "\\RR": "\\mathbb{R}" 
      "\\dx": "\\mathrm{d}x"
  show_datetime: true 
  

markdown_extensions:
  - attr_list
  - codehilite
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.details
  - pymdownx.blocks.tab
  - pymdownx.progressbar
  - pymdownx.tabbed
  - codehilite
  - shadcn.extensions.codexec
  - shadcn.extensions.echarts.alpha
  - fenced_code

plugins:
  - search
  - excalidraw
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
       - custom-skip-class-name
      auto_themed: false
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false