site_name: "nwabel"
site_url: https://nwabel.github.io/
repo_url: https://github.com/nwabel/nwabel.github.io

theme:
  name: shadcn
  custom_dir: overrides
  show_title: true
  show_stargazers: true
  pygments_style:
        light: shadcn-light
        dark: github-dark
  icon: heroicons:bug-ant
  favicon: assets/images/logo/logoku.svg
  topbar_sections: true
  katex_options:
    macros:
      "\\RR": "\\mathbb{R}" 
      "\\dx": "\\mathrm{d}x"
  show_datetime: true 

nav:
  - Home: index.md
  - Finding Nemo:
      - Index: finding/index.md
  - Wretap:
      - Index: wretap/index.md
      - DFIR (Blue Team):
          - Lab 1: wretap/dfir/lab1.md
      - Threat Hunting:
          - Lab 2: wretap/threat-hunting/lab2.md
  - Wiki:
      - Index: wiki/index.md
      - Kriptografi Intro: wiki/Kriptografi___Intro.md
  - Blok:
      - Index: blog/index.md
      - tes1: blog/1.md

markdown_extensions:
  - meta
  - attr_list
  - codehilite
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.details
  - pymdownx.blocks.tab
  - pymdownx.progressbar
  - pymdownx.tabbed
  - codehilite
  - shadcn.extensions.codexec
  - shadcn.extensions.echarts.alpha
  - fenced_code

plugins:
  - termynal
  - search
  - excalidraw
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
       - custom-skip-class-name
      auto_themed: false
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
  
extra_css:
  - https://unpkg.com/aos@2.3.4/dist/aos.css
  - assets/css/home.css
  - assets/css/fixes.css
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/aos@2.3.4/dist/aos.js
  - assets/js/fixes.js
  - assets/js/niwPost.js